name: kiosk_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3
  flutter_naver_map: ^1.4.1+1
  geolocator: ^14.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: 0.13.6
  provider: ^6.1.5
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
